config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#home'
  get 'home/about' => 'home/about'
  resources :books
  resources :users

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	#バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
	#presence trueは空欄の場合を意味する。
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

        validates :name, presence: true, length: { in: 2..20 }
        validates :introduction, length: { maximum: 50 }

         has_many :books, dependent: :destroy
         has_many :homes, dependent: :destroy
         attachment :profile_image # ここを追加（_idは含めません）
         def email_required?
            false
  		 end

  	     def email_changed?
            false
         end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?
  def after_sign_in_path_for(resource)
    user_path(current_user.id ) # ログイン後に遷移するpathを設定
  end
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    before_action :authenticate_user!
  def new
    @book = Book.new
    end
    def create
      @book = Book.new(book_params)
      @book.user_id = current_user.id
      if @book.save
          flash[:notice] = "Book was successfully created."
          redirect_to book_path(@book.id)
        else
            @user = current_user
          @books = Book.all
          render 'index'
        end
    end
    def index
      @book = Book.new
    @books = Book.all
        @user = current_user
    end
    def show
        @new_book = Book.new
      @book = Book.find(params[:id])
        @user = @book.user
    end
    def edit
      @book = Book.find(params[:id])
        if @book.user.id != current_user.id
           redirect_to books_path
            
        end
    end
    def destroy
      book = Book.find(params[:id])
        book.destroy
      redirect_to books_path
    end
    def update
        @book = Book.find(params[:id])
        if @book.update(book_params)
          flash[:notice] = "Book was successfully created."
          redirect_to book_path(@book)
        else
          render 'edit'
        end
    end

    private
    def book_params
        params.require(:book).permit(:title, :body )
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def home


	end
	def about
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!, only: [:index, :show, :edit]
    def new
    @user = user.new
    end
    def create
      @user = User.new(user_params)
      @user.user_id = current_user.id
        if  @user.save
            flash[:notice] = "Book was successfully created."
          redirect_to users_path
        else
            @user = current_user
            @users = Book.all
            flash[:notice] = "error"
            render 'index'
        end
    end
    def index
        @book = Book.new
        @users = User.all
        @user = current_user
    end
    def show
      @new_book = Book.new
        @user = User.find(params[:id])
        @books = @user.books
    end
    def edit
      @user = User.find(params[:id])
        if @user.id != current_user.id
           redirect_to user_path(current_user)
            
        end
    end
    def update
        @user = User.find(params[:id])
        if @user.update(user_params)
            flash[:notice] = "User was successfully created."
            redirect_to user_path(@user)
        else
            render 'edit'
        end
    end

    private
    def user_params
        params.require(:user).permit(:name, :introduction, :profile_image )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_newform.html.erb
<div class="error_messages">
  <% if book.errors.any? %>
    <div class="error_explanation">
      <h2><%= book.errors.count %>errors prohibited this book from being saved:</h2>
      <ul>
        <% book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
</div> 
<%= form_for(book) do |f| %>
                      <h4>Title</h4>
                              <%= f.text_field :title %>
                      <h4>opinion</h4>
                              <%= f.text_area :body %>
                      <p>
                            <%= f.submit 'Create Book',class:'btn btn-primary col-xs-15' %>
                      </p>
                            <% end %>

app/views/books/edit.html.erb
<div class="error_messages">
  <% if @book.errors.any? %>
    <div class="error_explanation">
      <h2><%= @book.errors.count %>errors prohibited this book from being saved:</h2>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
</div> 
<h1>Editing Book</h1>
<%= form_for(@book) do |f| %>
<h4>Title</h4>
    <%= f.text_field :title %>
 
    <h4>opinion</h4>
    <%= f.text_area :body %>
<p>
 <%= f.submit 'Update Book' %>
</p>
<% end %>
	<%=link_to "Show", book_path(@book.id) %>
	<%=link_to "Back", books_path %>

app/views/books/index.html.erb
 <div class="container">
    <p id="notice"></p>
    <div class="error_messages">
  <% if @book.errors.any? %>
    <div class="error_explanation">
      <h2><%= @book.errors.count %>errors prohibited this book from being saved:</h2>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
</div> 
      <div class="row">
          <div class="col-xs-3">
              <h2>User info</h2>
              <%= render "users/profile", user: current_user %>
                  <h2>New book</h2>
              <%= render "books/newform", book: @book %>
          </div>
          <div class="col-xs-9">
                <h2>Books</h2>
                <table>
                    <thead>
                        <tr>
                          <th>Title</th>
                          <th>Opinion</th>
                          <th colpan="3"></th>
                        </tr>
                    </thead>
                    <tbody>
                        <% @books.each do |book| %>
                            <tr>
                                <td><%= link_to user_path(book) do %>
                                    <%= attachment_image_tag @user , :profile_image , fallback: "no_image.jpg" %>
                                    <% end %>
                                </td>
                                <td><%= link_to book_path(book) do %><%= book.title %>
                                    <% end %>
                                </td>
                                <td><%= book.body %></td>
                            </tr>
                        <% end %>
                    </tbody>
                </table>
          </div>
      </div>
  </div>

app/views/books/show.html.erb
<div class="container">
		<div class="error_messages">
			<% if @book.errors.any? %>
				<div class="error_explanation">
				      <h2><%= @book.errors.count %>errors prohibited this book from being saved:</h2>
				      <ul>
				<% @book.errors.full_messages.each do |message| %>
				          <li><%= message %></li>
				<% end %>
				      </ul>
				    </div>
			<% end %>
		</div> 
	<div class="row">

		<div class="col-xs-3">
			User info
		    <h2>User info</h2>
		    <%= render "users/profile", user: @user %>
			<h2>New book</h2>
			<!-- form_for部分 -->
			<%= render "books/newform", book: @new_book %>
		</div>
		<div class="col-xs-9">
			<h2>Book detail</h2>
				<table class="table">
					<tbody>
						<tr>
							<td>
									<%= attachment_image_tag @book.user , :profile_image , fallback: "no_image.jpg" %>
								<br>
								<%= link_to user_path(@user) do %><%= @user.name %>
								<% end %>
							</td>
								<td><%= @book.title %></td>
								<td><%= @book.body %></td>
								<% if @book.user.id == current_user.id %>
								<td><%= link_to "Edit", edit_book_path(@book),class:'btn-sm btn-success edit_book_31537' %></td>
						        <td><%= link_to "Destroy", book_path(@book),class:'btn-sm btn-danger destroy_book_31537 ',method: :delete, "data-confirm" => "本当に削除しますか？" %></td>
						  		<% end %>
						</tr>
					</tbody>
				</table>
		</div>
	</div>
</div>

app/views/home/about.html.erb
<h1>welcome to<span class="glyphicon glyphicon-book"></span>
<strong>Bookers</strong>  !!</h1>

app/views/home/home.html.erb
<div class="row">
	<div class="main col-md-offset-3 col-md-6">
		<h1>welcome to<span class="glyphicon glyphicon-book"></span>
			<strong>Bookers</strong>  !!</h1>
			<p>In <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>,</p>
			<p>you can share and exchange your opinions , inpressions , and emotions</p>
			<p>about varioius books!</p>

			<div class="btn-wrapper">
				<div class="row">
					<p><%=link_to "Log in", new_user_session_path, class: "btn btn-info col-xs-10 col-xs-offset-1" %></p>
				</div>
				<div class="row">
					<p><%=link_to "Sign Up", new_user_registration_path, class: "btn btn-success col-xs-10 col-xs-offset-1" %></p>
				</div>
			</div>

	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">

        <nav class="nav navbar-nav navbar-left">
          <span>Bookers</span>
        </nav>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li><%= link_to ' home', user_path(current_user.id), class: 'glyphicon glyphicon-home home' %></li>
              <li><%= link_to ' users', users_path, class: 'glyphicon glyphicon-user users' %></li>
              <li><%= link_to ' books', books_path, class: 'glyphicon glyphicon-book books' %></li>
              <li><%= link_to ' logout', destroy_user_session_path, method: :delete, class: 'glyphicon glyphicon-log-out logout' %></li>
            <% else %>
              <li><%= link_to ' home', root_path, class: 'glyphicon glyphicon-home home' %></li>
              <li><%= link_to ' about', home_about_path, class: 'glyphicon glyphicon-link about' %></li>
              <li><%= link_to ' Sign up', new_user_registration_path, class: 'glyphicon glyphicon-edit sign_up' %></li>
              <li><%= link_to ' login', new_user_session_path, class: 'glyphicon glyphicon-log-in sign_in' %></li>
            <% end %>
          </ul>
        </nav>

      </div>
    </header>

    <div class="container">
      <p id="notice"><%= notice %></p>
        <%=yield%>
    </div>

    <footer>
      <div class="container">
        <div class="row">
          <div class="col-xs-3 col-xs-offset-9">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/_profile.html.erb
<table class="table">
<%= attachment_image_tag current_user , :profile_image , fallback: "no_image.jpg" %>
                  <tbody> 
                    <tr>
                        <th>name</th>
                        <th><%= user.name %><th>
                    </tr>
                    <tr>
                        <th>introduction</th>
                        <th><%= user.introduction %></th>
                    </tr>
                  </tbody>
                </table>
                  	    <p>
                            <td><%= link_to "edit", edit_user_path(current_user),class:'col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_19746' %></td> 
                        </p>

app/views/users/edit.html.erb
<div class="error_messages">
  <% if @user.errors.any? %>
    <div class="error_explanation">
      <h2><%= @user.errors.count %>errors prohibited this book from being saved:</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
</div> 
<h1>Editing Book</h1>
  <%= form_for(@user) do |f| %>
      <h2>User info</h2>
      <p>Name<%= f.text_area :name %></p>
        <p>Image
          <%= f.attachment_field :profile_image %>
        </p>
        <p>Introduction<%= f.text_area :introduction %></p>
      　<p>
          <%= f.submit 'Update User' %>
      　</p>
  <% end %>

app/views/users/index.html.erb
<div class="body">
  <div class="container">
     <p id="notice"></p>
      <div class="error_messages">
        <% if @book.errors.any? %>
              <div class="error_explanation">
                <h2><%= @book.errors.count %>errors prohibited this book from being saved:</h2>
                <ul>
                  <% @book.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>
          </div> 
        <div class="row">
          <div class="col-xs-3">
            <h2>User info</h2>
              <%= render "users/profile", user: current_user %>
                      <h2>New book</h2>
              <%= render "books/newform", book: @book %>
  </div>
          <div class="col-xs-9">
                            <h2>Users</h2>
                            <table class="table">
                                <thead>
                                      <tr>
                                        <th>image</th>
                                        <th>name</th>
                                        <th colspan="3"></th>
                                      </tr>
                                </thead>
                                  <tbody>
                                    <% @users.each do |u| %>
                                          <tr>
                                              <td><%= attachment_image_tag u , :profile_image , fallback: "no_image.jpg" %></td>
                                              <td><%= u.name %></td>
                                              <td><%= link_to "Show", user_path(u) %></td>
                                          </tr>
                                    <% end %>
                                  </tbody>
                              </table>
                              </div>
                          </div>
                        </div>
                      </div>
              </div>
            </div>
          </div>
      </div>
    </div>
  </div>
</body>

app/views/users/show.html.erb
<div class="body">
	<% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>
  <div class="container">
     <p class="notice"></p>
     		<div class="error_messages">
				<% if @new_book.errors.any? %>
				    <div class="error_explanation">
				      <h2><%= @new_book.errors.count %>errors prohibited this book from being saved:</h2>
				      <ul>
				    <% @new_book.errors.full_messages.each do |message| %>
				          <li><%= message %></li>
				    <% end %>
				      </ul>
				    </div>
				<% end %>
			</div> 
      	<div class="row">
          	<div class="col-xs-3">
		    	<h2>User info</h2>
		    	<%= render "users/profile", user: @user %>
			<h2>New book</h2>
			<!-- form_for部分 -->
				<%= render "books/newform", book: @new_book %>
	</div>

				<div class="col-xs-9">
					<h2>Books</h2>
						<table class="table table-hover table-inverse">
							<thead>
								<tr>
									<th></th>
									<th>Title</th>
									<th>Opinion</th>
									<th colspan="3"></th>
								</tr>
							</thead>
								<tbody>
									<% @books.each do |b| %>
										<tr>
											<td><%= attachment_image_tag b.user , :profile_image , fallback: "no_image.jpg" %></td>
											<td><%= link_to book_path(b) do %><%= b.title %>
												<% end %>
											</td>
											<td><%= b.body %></td>
										</tr>
									<% end %>
								</tbody>
					</table>
				</div>
			</div>		
		</div>

	</div>
</div>